namespace SRMultiplayer.Packets
{
    public enum PacketType : ushort
    {
        // Base SRMP
        Unknown = 0,
        Authentication = 1,
        PlayerJoined = 2,
        PlayerLeft = 3,
        PlayerPosition = 4,
        PlayerLoaded = 5,
        PlayerAnimation = 6,
        PlayerFX = 7,
        PlayAudio = 8,
        ActorSpawn = 9,
        ActorDestroy = 10,
        RegionOwner = 11,
        RegionChange = 12,
        ActorPosition = 13,
        ActorOwner = 14,
        LandPlots = 15,
        LandPlotAsh = 16,
        LandPlotCollect = 17,
        LandPlotFeederSpeed = 18,
        LandPlotSiloRemove = 19,
        LandPlotSiloInsert = 20,
        LandPlotSiloSlot = 21,
        LandPlotReplace = 22,
        LandPlotUpgrade = 23,
        LandPlotPlantGarden = 24,
        LandPlotStartCollection = 25,
        WorldData = 26,
        GlobalFX = 27,
        IncinerateFX = 28,
        AccessDoors = 29,
        Gordos = 30,
        AccessDoorOpen = 31,
        WorldTime = 32,
        WorldFastForward = 33,
        PuzzleSlotFilled = 34,
        PuzzleSlots = 35,
        WorldProgress = 36,
        PediaShowPopup = 37,
        PediaUnlock = 38,
        PlayerUpgrade = 39,
        WorldKey = 40,
        WorldMapUnlock = 41,
        PlayerUpgradeUnlock = 42,
        PlayerCurrency = 43,
        PuzzleGateActivate = 44,
        WorldSwitchActivate = 45,
        WorldSelectPalette = 46,
        WorldSwitches = 47,
        Gadgets = 48,
        FashionAttach = 49,
        FashionDetachAll = 50,
        GadgetAdd = 51,
        GadgetAddBlueprint = 52,
        GadgetRemove = 53,
        GadgetRotation = 54,
        GadgetSpend = 55,
        GadgetRefinerySpend = 56,
        GadgetSpawn = 57,
        PlayerCurrencyDisplay = 58,
        LandPlotSiloAmmoAdd = 59,
        LandPlotSiloAmmoRemove = 60,
        LandPlotSiloAmmoClear = 61,
        GadgetExtractorUpdate = 62,
        DroneAmmoAdd = 63,
        DroneAmmoRemove = 64,
        DroneAmmoClear = 65,
        DroneAnimation = 66,
        DronePrograms = 67,
        DroneLiquid = 68,
        DroneStationEnabled = 69,
        DronePosition = 70,
        DroneActive = 71,
        ActorResourceAttach = 72,
        ActorResourceState = 73,
        Actors = 74,
        ActorReproduceTime = 75,
        ActorFeral = 76,
        ActorEmotions = 77,
        WorldDecorizer = 78,
        GadgetTurrets = 79,
        GadgetSnareGordo = 80,
        GadgetSnareAttach = 81,
        WorldMarketSold = 82,
        WorldMarketPrices = 83,
        TreasurePodOpen = 84,
        TreasurePods = 85,
        WorldCredits = 86,
        WorldMailSend = 87,
        WorldMailRead = 88,
        ExchangePrepareDaily = 89,
        ExchangeOffer = 90,
        ExchangeTryAccept = 91,
        ExchangeClear = 92,
        ExchangeOffers = 93,
        ExchangeBreak = 94,
        GordoEat = 95,
        Oasis = 96,
        OasisLive = 97,
        FireColumnActivate = 98,
        FireStormMode = 99,
        GingerAction = 100,
        KookadobaAction = 101,
        ActorFX = 102,
        WorldDecorizerSetting = 103,
        GingerAttach = 104,
        KookadobaAttach = 105,
        EchoNetTime = 106,
        GadgetEchoNetTime = 107,
        RaceActivate = 108,
        RaceEnd = 109,
        RaceTime = 110,
        RaceTrigger = 111,
        PlayerChat = 112,
        KickPlayer = 113,
        
        // Mod support - VR
        VRPositions = 114,
        
        // Mod support - Nicknames
        SetNickname = 115,
        
        // Mod support - HolySlimes
        SpiritSlimeMode = 116,

        // Latency measurement and the fast world-clock sync that rides on it
        Ping = 117,
        Pong = 118,
        PlayerPings = 119,
        NameSuggestions = 120,
    }
}
